name = "Section_3_8_Argument_Passing"


[build]
auto-executables = true
auto-tests = true
auto-examples = true

[install]
library = false

[[executable]]
name="Section_3_8_Argument_Passing"
source-dir="app"
main="section_3_8_argument_passing.f90"

